- name: restart ipfs
  service: name=ipfs state=stopped
  notify:
    - unmount ipfs
    - unmount ipns
    - start ipfs
- name: start ipfs
  service: name=ipfs state=started
  become: true
- name: unmount ipfs
  mount: name=/ipfs state=unmounted src=none fstype=none
  become: true
  when: ipfs_mount
- name: unmount ipns
  mount: name=/ipns state=unmounted src=none fstype=none
  become: true
  when: ipfs_mount
