---
- name: Install elasticsearch repository key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present id=D88E42B4
- name: Install apt-transport-https
  apt: name=apt-transport-https state=present
- name: Install ca-certificates
  apt: name=ca-certificates state=latest
- name: Add elasticsearch repository
  apt_repository: repo='deb https://artifacts.elastic.co/packages/5.x/apt stable main' state=present update_cache=yes
- name: Install JRE
  apt: pkg=default-jre state=present
- name: Install elasticsearch
  apt: pkg=elasticsearch state=latest
  notify: restart elasticsearch
  register: es_installed
- name: Create snapshot directory
  file: path=/var/lib/elasticsearch/backup state=directory owner=elasticsearch group=elasticsearch
- name: Check plugins
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin list -s
  register: es_plugins
- name: Remove S3 repository plugin
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin remove -s repository-s3
  when: es_installed.changed and 'repository-s3' in es_plugins
- name: Install S3 repository plugin
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install -s repository-s3
  when: es_installed.changed
  notify: restart elasticsearch
- name: Configuration
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch
- name: Increase elasticsearch heap size minimum
  lineinfile: dest=/etc/elasticsearch/jvm.options regexp='-Xms' line='-Xms{{ es_heap_size }}'
  notify: restart elasticsearch
- name: Increase elasticsearch heap size maximum
  lineinfile: dest=/etc/elasticsearch/jvm.options regexp='-Xmx' line='-Xmx{{ es_heap_size }}'
  notify: restart elasticsearch
# - name: Stretch elasticsearch memory limit
#   lineinfile: dest=/etc/systemd/system/elasticsearch.service.d/50-MemoryLimit.conf regexp='^MemoryLimit' line='MemoryLimit=2684354560'
#   notify: restart elasticsearch
- name: Enable elasticsearch service
  service: name=elasticsearch enabled=yes state=started
