---
- name: Install nodesource repository key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
- name: Add nodesource repository
  apt_repository: repo='deb https://deb.nodesource.com/node_9.x xenial main' state=present update_cache=yes
- name: Install Node
  apt:
    name: nodejs
    state: latest
- name: Create destination folder for search api
  file: path={{ api_install_path }} state=directory
- name: Sync ipfs-search api
  synchronize: src=../../../api/ dest={{ api_install_path }} times=yes partial=yes archive=no recursive=yes
  notify:
    - restart ipfs-search
    - restart ipfs-metadata
- name: Install search API
  npm:
    path: "{{ api_install_path }}/search"
  notify: restart ipfs-search
- name: Install metadata API
  npm:
    path: "{{ api_install_path }}/metadata"
  notify: restart ipfs-metadata
- name: Create ipfs-search group.
  group: name=ipfs-search system=true state=present
- name: Create ipfs-search user.
  user: name=ipfs-search comment="ipfs-search api" group=ipfs-search system=true state=present home=/nonexistent shell=/usr/sbin/nologin
- name: Install ipfs-search service
  template: src=ipfs-search.service dest=/etc/systemd/system/ipfs-search.service
  notify: restart ipfs-search
- name: Install ipfs-metadata service
  template: src=ipfs-metadata.service dest=/etc/systemd/system/ipfs-metadata.service
  notify: restart ipfs-metadata
- name: Install nginx configuration
  template: src=nginx-api.conf dest=/etc/nginx/sites-available/api.conf
  notify: restart nginx
- name: Enable nginx configuration
  file:
    path: /etc/nginx/sites-enabled/api.conf
    src: /etc/nginx/sites-available/api.conf
    state: link
  notify: restart nginx
- name: Enable search service
  service: name=ipfs-search enabled=yes state=started
- name: Enable metadata service
  service: name=ipfs-metadata enabled=yes state=started

