---
- name: Install elasticsearch repository key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present id=D88E42B4
- name: Add elasticsearch repository
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/5.x/debian stable main' state=present update_cache=yes
- name: Install JRE
  apt: pkg=default-jre state=present
- name: Install elasticsearch
  apt: pkg=elasticsearch state=latest
- name: Create snapshot directory
  file: path=/var/lib/elasticsearch/backup state=directory owner=elasticsearch group=elasticsearch
- template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch
- template: src=logging.yml dest=/etc/elasticsearch/logging.yml
  notify: restart elasticsearch
- name: Increase elasticsearch heap size minimum
  lineinfile: dest=/etc/elasticsearch/jvm.options regexp='-Xms' line='-Xms{{ es_heap_size }}'
  notify: restart elasticsearch
- name: Increase elasticsearch heap size maximum
  lineinfile: dest=/etc/elasticsearch/jvm.options regexp='-Xmx' line='-Xmx{{ es_heap_size }}'
  notify: restart elasticsearch
# - name: Stretch elasticsearch memory limit
#   lineinfile: dest=/etc/systemd/system/elasticsearch.service.d/50-MemoryLimit.conf regexp='^MemoryLimit' line='MemoryLimit=2684354560'
#   notify: restart elasticsearch
- name: Enable elasticsearch service
  service: name=elasticsearch enabled=yes state=started
