---
- name: Create libexec directory
  file: path={{ ipfs_tika_path }} state=directory owner=root group=root mode=755
- name: Download ipfs-tika
  get_url: url={{ ipfs_tika_mirror}}{{ ipfs_tika_jar }} dest={{ ipfs_tika_path }}/{{ ipfs_tika_jar }} owner=root group=root checksum="sha1:{{ ipfs_tika_sha1 }}"
  notify: restart ipfs-tika
  register: download
- include_role:
    name: annotate
  vars:
    role: tika
    version: "{{ ipfs_tika_jar }}"
    action: upgrade
  when: download.changed
- group: name=ipfs-tika system=true state=present
- user: name=ipfs-tika comment="IPFS tika daemon" group=ipfs-tika system=true state=present home="/nonexistent" shell=/usr/sbin/nologin
- name: systemd service
  template: src=ipfs-tika.service dest=/etc/systemd/system/ipfs-tika.service
  notify: restart ipfs-tika
- service: name=ipfs-tika enabled=yes state=started
  notify: restart ipfs-tika
- name: Enable ipfs-tika stale temp removal
  cron:
    name: Delete stale temp files
    minute: "23"
    hour: "*"
    job: "find /tmp -maxdepth 1 -user ipfs-tika -cmin +60 -name '*.tmp' -delete"
    state: present
    cron_file: /etc/crontab
    user: ipfs-tika
  become: true
