---
- name: Install RabbitMQ repository key
  apt_key: url=https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey state=present id=F6609E60DC62814E
- name: Add RabbitMQ repository
  apt_repository: repo='deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ xenial main' state=present update_cache=yes
- name: Install Erlang repository key
  apt_key: url=https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc state=present id=D208507CA14F4FCA
- name: Add Erlang repository
  apt_repository: repo='deb https://packages.erlang-solutions.com/ubuntu xenial contrib' state=present update_cache=yes
- name: Install required packages
  apt: pkg=rabbitmq-server state=latest
  notify: restart rabbitmq
- name: Configuration file
  template: src=rabbitmq.config dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbitmq
- name: Enable required services
  service: name=rabbitmq-server enabled=yes state=started
- name: Setup rabbitmq admin user
  rabbitmq_user: user=admin
                 password=admin
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
                 tags=administrator
  notify: restart rabbitmq
- name: Enable rabbitmq plugins
  rabbitmq_plugin: names=rabbitmq_management,rabbitmq_shovel,rabbitmq_shovel_management state=enabled
  notify: restart rabbitmq
